AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for language-learning-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 512

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  PreSignUpFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./Lambda/PreSignUp/
      Handler: bootstrap
      Runtime: dotnet8
      Architectures:
        - x86_64
      MemorySize: 512

  UpdateLanguageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./Lambda/UpdateLanguage/
      Handler: bootstrap
      Runtime: dotnet8
      Architectures:
        - x86_64
      MemorySize: 512

  GetUserLanguagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./Lambda/GetUserLanguages/
      Handler: bootstrap
      Runtime: dotnet8
      Architectures:
        - x86_64
      MemorySize: 512

  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./Lambda/GetUser/
      Handler: bootstrap
      Runtime: dotnet8
      Architectures:
        - x86_64
      MemorySize: 512

  UpdateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./Lambda/UpdateUser/
      Handler: bootstrap
      Runtime: dotnet8
      Architectures:
        - x86_64
      MemorySize: 512
  
  RemoveUserLanguagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./Lambda/RemoveUserLanguage/
      Handler: bootstrap
      Runtime: dotnet8
      Architectures:
        - x86_64
      MemorySize: 512
  
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
  
  Outputs:
    PreSignUpFunction:
      Description: "PreSignUp Lambda Function name"
      Value:
        Ref: PreSignUpFunction
        
    PreSignUpRole:
      Description: "PreSignUp Lambda Function Role"
      Value:
        Fn::GetAtt:
          - PreSignUpFunction
          - Role
    UpdateLanguageFunction:
      Description: "UpdateLanguage Lambda Function name"
      Value:
        Ref: UpdateLanguageFunction
        
    UpdateLanguageRole:
        Description: "UpdateLanguage Lambda Function Role"
        Value:
            Fn::GetAtt:
            - UpdateLanguageFunction
            - Role
    
    GetUserLanguagesFunction:
        Description: "GetUserLanguages Lambda Function name"
        Value:
            Ref: GetUserLanguagesFunction
    
    GetUserLanguagesRole:
        Description: "GetUserLanguages Lambda Function Role"
        Value:
            Fn::GetAtt:
            - GetUserLanguagesFunction
            - Role
    
    GetUserFunction:
        Description: "GetUser Lambda Function name"
        Value:
            Ref: GetUserFunction
            
    GetUserRole:
        Description: "GetUser Lambda Function Role"
        Value:
            Fn::GetAtt:
            - GetUserFunction
            - Role
              
    UpdateUserFunction:
        Description: "UpdateUser Lambda Function name"
        Value:
            Ref: UpdateUserFunction
            
    UpdateUserRole:
        Description: "UpdateUser Lambda Function Role"
        Value:
            Fn::GetAtt:
            - UpdateUserFunction
            - Role
              
    RemoveUserLanguagesFunction:
        Description: "RemoveUserLanguages Lambda Function name"
        Value:
            Ref: RemoveUserLanguagesFunction
            
    RemoveUserLanguagesRole:
        Description: "RemoveUserLanguages Lambda Function Role"
        Value:
            Fn::GetAtt:
            - RemoveUserLanguagesFunction
            - Role