AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for language-learning-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 512

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
      
Resources:
  PreSignUpFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./Lambda/LambdaStartup/
      Handler: bootstrap
      Environment:
        Variables:
          ANNOTATIONS_HANDLER: "PreSignUpTrigger"
      Runtime: dotnet8
      Architectures:
        - x86_64
      MemorySize: 512
  
  UpdateLanguageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./Lambda/LambdaStartup/
      Handler: bootstrap
      Environment:
        Variables:
          ANNOTATIONS_HANDLER: "UpdateLanguage"
      Runtime: dotnet8
      Architectures:
        - x86_64
      MemorySize: 512
  
  GetUserLanguagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./Lambda/LambdaStartup/
      Handler: bootstrap
      Environment:
        Variables:
          ANNOTATIONS_HANDLER: "GetUserLanguages"
      Runtime: dotnet8
      Architectures:
        - x86_64
      MemorySize: 512
  
  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./Lambda/LambdaStartup/
      Handler: bootstrap
      Environment:
        Variables:
          ANNOTATIONS_HANDLER: "GetUser"
      Runtime: dotnet8
      Architectures:
        - x86_64
      MemorySize: 512
  
  UpdateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./Lambda/LambdaStartup/
      Handler: bootstrap
      Environment:
        Variables:
          ANNOTATIONS_HANDLER: "UpdateUser"
      Runtime: dotnet8
      Architectures:
        - x86_64
      MemorySize: 512

  RemoveUserLanguageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./Lambda/LambdaStartup/
      Environment:
        Variables:
          ANNOTATIONS_HANDLER: "RemoveLanguage"
      Handler: bootstrap
      Runtime: dotnet8
      Architectures:
        - x86_64
      MemorySize: 512

  AddVocabularyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./Lambda/LambdaStartup/
      Handler: bootstrap
      Environment:
        Variables:
          ANNOTATIONS_HANDLER: "AddVocabulary"
      Runtime: dotnet8
      Architectures:
        - x86_64
      MemorySize: 512

  RemoveVocabularyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./Lambda/LambdaStartup/
      Handler: bootstrap
      Environment:
        Variables:
          ANNOTATIONS_HANDLER: "RemoveVocabulary"
      Runtime: dotnet8
      Architectures:
        - x86_64
      MemorySize: 512

  GetVocabularyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./Lambda/LambdaStartup/
      Handler: bootstrap
      Environment:
        Variables:
          ANNOTATIONS_HANDLER: "GetVocabulary"
      Runtime: dotnet8
      Architectures:
        - x86_64
      MemorySize: 512
      
  GenerateSentencesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./Lambda/LambdaStartup/
      Handler: bootstrap
      Environment:
        Variables:
          ANNOTATIONS_HANDLER: "GenerateSentences"
      Runtime: dotnet8
      Architectures:
        - x86_64
      MemorySize: 512
      
  VerifySentenceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./Lambda/LambdaStartup/
      Handler: bootstrap
      Environment:
        Variables:
          ANNOTATIONS_HANDLER: "VerifySentence"
      Runtime: dotnet8
      Architectures:
        - x86_64
      MemorySize: 512
