version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::021891610553:user/pipeline"
permissions_provider = "AWS IAM"

[staging.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::021891610553:role/aws-sam-cli-managed-sttg-pipe-PipelineExecutionRole-BtxVshGQRTdm"
cloudformation_execution_role = "arn:aws:iam::021891610553:role/aws-sam-cli-managed-sttg--CloudFormationExecutionRo-CpMUVuR6YY5P"
artifacts_bucket = "aws-sam-cli-managed-staging-pipeli-artifactsbucket-kixxajb9vq0q"
image_repository = ""
region = "eu-west-2"
